name: Dependency Submission
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-submission-action@v1
        with:
          directory: .
